<Project>
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>

    <IsPackable>false</IsPackable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <IncludeSource>true</IncludeSource>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <Deterministic>true</Deterministic>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <DebugType>portable</DebugType>

    <Authors>Elysium Coding</Authors>
    <Company>Elysium Coding</Company>
    <RepositoryUrl>https://github.com/mape1402/wolfauth</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/mape1402/wolfauth</PackageProjectUrl>
    <PackageReleaseNotes>https://github.com/mape1402/wolfauth/releases</PackageReleaseNotes>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>wolfauth-icon.png</PackageIcon>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageTags>wolfauth;dotnet;authentication;authorization;provisioning;library</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" Visible="false" PackagePath="" />
    <None Include="../../assets/wolfauth-icon.png" Pack="true" Visible="false" PackagePath="" />
  </ItemGroup>

  <PropertyGroup>
    <Version Condition="'$(MinVerVersion)' != ''">$(MinVerVersion)</Version>
    <Version Condition="'$(MinVerVersion)' == ''">0.1.0</Version>
    <MinVerTagPrefix>v</MinVerTagPrefix>
    <MinVerMinimumMajorMinor>0.1</MinVerMinimumMajorMinor>
    <MinVerBuildMetadata>build.{DateTime:yyyyMMddHHmmss}</MinVerBuildMetadata>
    <MinVerIsRelease>false</MinVerIsRelease>
  </PropertyGroup>
</Project>
