<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <UserSecretsId>wolfauth-entra-id-web-site-sample</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="8.0.22" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\WolfAuth.AspNetCore\WolfAuth.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\WolfAuth.Microsoft.EntraId\WolfAuth.Microsoft.EntraId.csproj" />
    <ProjectReference Include="..\..\src\WolfAuth\WolfAuth.csproj" />
  </ItemGroup>

</Project>
